echo "Test 0 (Incorrect usage):";
time py.exe ../src/main.py;
echo "=====================================";
echo "Test 1 (Empty input):";
time py.exe ../src/main.py -q input/test1.txt output/test1.txt;
echo "=====================================";
echo "Test 2 (3 hardcoded):";
time py.exe ../src/main.py -q input/test2.txt output/test2.txt;
echo "=====================================";
echo "Test 3 (Invalid input):";
time py.exe ../src/main.py -q input/test3.txt output/test3.txt;
echo "=====================================";
echo "Test 4 (9 hardcoded):";
time py.exe ../src/main.py -q input/test4.txt output/test4.txt;
echo "=====================================";
echo "Test 5 (50 randomized):";
time py.exe ../src/main.py -q -r input/test5.txt output/test5.txt;
echo "=====================================";
echo "Test 6 (50 randomized):";
time py.exe ../src/main.py -q -r input/test6.txt output/test6.txt;
echo "=====================================";
echo "Test 7 (1000 randomized):";
time py.exe ../src/main.py -q -r input/test7.txt output/test7.txt;
echo "=====================================";
echo "Test 8 (1000 randomized):";
time py.exe ../src/main.py -q -r input/test8.txt output/test8.txt;
echo "=====================================";
echo "Test 9 (10000 randomized):";
time py.exe ../src/main.py -q -r input/test9.txt output/test9.txt;
echo "=====================================";
echo "Test 10 (10000 randomized):";
time py.exe ../src/main.py -q -r input/test10.txt output/test10.txt;